name: fin-ai

services:
  fin-ai:
    container_name: fin-ai-api
    build:
      context: .
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: bitnami/postgresql:16
    container_name: fin-ai-postgres
    environment:
      POSTGRES_DB: fin-ai
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - fin-ai_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  fin-ai_postgres_data:
